# Generated by Django 5.0.2 on 2024-02-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="employees",
                to="restaurants.restaurant",
            ),
        ),
    ]
